name: Deploy platform-extension-static-bundles

on:
  push:
    paths:
      - 'packages/platform-extension-static-bundles/**'
    branches: [ master ]
  workflow_dispatch:

env:
  ResourceGroupName: rg_web_mwd_dev
  ResourceGroupRegionLocation: francecentral
  AppServicePlanName: ASP-az-ct-bundles
  WebAppName: platform-extension-static-bundles
  Tier: Standard
  WorkerSize:  Medium #Small, Medium, Large, ExtraLarge
  NumberofWorkers: 2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn install --immutable

    - name: Building
      env: 
         APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      run: |
         cd packages/platform-extension-static-bundles
         yarn build
      
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Create Az Web App 
      uses: azure/powershell@v1
      id: ACR_step
      with:
        azPSVersion: "latest"
        inlineScript: |
           $AppServicePlan = Get-AzAppServicePlan -Name ${{ env.AppServicePlanName }} -ResourceGroupName ${{ env.ResourceGroupName }} -ErrorAction SilentlyContinue
           if($AppServicePlan -eq $null){
              $AppServicePlan = New-AzAppServicePlan -Linux -Tier ${{ env.Tier }} -NumberofWorkers ${{ env.NumberofWorkers }} -WorkerSize ${{ env.WorkerSize }} -ResourceGroupName ${{ env.ResourceGroupName }} -Name ${{ env.AppServicePlanName }} -Location ${{ env.ResourceGroupRegionLocation }}
           }
           $webApp = Get-AzWebApp -ResourceGroupName ${{ env.ResourceGroupName }} -Name ${{ env.WebAppName }} -ErrorAction SilentlyContinue
           if($webApp -eq $null){
              $webApp = New-AzWebApp -ResourceGroupName ${{ env.ResourceGroupName }} -Name ${{ env.WebAppName }}" -Location${{ env.ResourceGroupRegionLocation }} -AppServicePlan ${{ env.AppServicePlanName }}
           }
           #Set-AzWebApp -Name "MyWebApp" -ResourceGroupName "MyResourceGroup" -AppSettings@{"MyKey"="MyValue"}
           az webapp deployment list-publishing-profiles --xml --resource-group ${{ env.ResourceGroupName }} --name ${{ env.WebAppName }} | Out-File -FilePath .\profile.txt
           $profile = Get-Content .\profile.txt -Raw
           Write-host "Profile: $profile"
           echo "PROFILE=$profile" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
            
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2.2.3
      with: 
         app-name: ${{ env.WebAppName }}
         publish-profile: ${{ env.PROFILE }}
         package: packages/platform-extension-static-bundles
          
    - name: logout
      run: |
        az logout
      if: always()
