name: Blob storage website CI

on:
  push:
    paths:
      - 'packages/platform-extension-static-bundles/**'
    branches: [ master ]
  workflow_dispatch:

env:
  ResourceGroupName: rg_web_mwd_dev
  ResourceGroupRegionLocation: francecentral
  StorageAccountName: stctcustomappbundles
  SkuName: "Standard_LRS"
  Kind: "StorageV2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - uses: actions/checkout@v3

    - name: Change directory
      run: cd packages/platform-extension-static-bundles/
      
    - name: Install dependencies
      run: yarn install --immutable

    - name: Building
      env: 
         APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      run: yarn build
      
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create Storage account 
      uses: azure/powershell@v1
      id: SA_step
      with:
        azPSVersion: "latest"
        inlineScript: |
          $storageAccount = Get-AzStorageAccount -ResourceGroupName ${{ env.ResourceGroupName }} -Name ${{ env.StorageAccountName }} -ErrorAction SilentlyContinue
          if($storageAccount -eq $null){
             $storageAccount = New-AzStorageAccount -ResourceGroupName ${{ env.ResourceGroupName }} -Name ${{ env.StorageAccountName }} -Location ${{ env.ResourceGroupRegionLocation }} -SkuName ${{ env.SkuName }} -Kind ${{ env.Kind }}
             Enable-AzStorageStaticWebsite -Context $storageAccount.Context -IndexDocument "index.html" -ErrorDocument404Path "index.html"
          }
          Write-host "Web endpoints: $storageAccount.PrimaryEndpoints"
   
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name ${{ env.StorageAccountName }} --auth-mode key -s '$web' 
          az storage blob upload-batch --account-name ${{ env.StorageAccountName }} --auth-mode key -d '$web' -s public/

    - name: logout
      run: |
        az logout
      if: always()
